### ISSUE TITLE
Create AddToDoListItemBar Component

### ISSUE THREAD

**Issue by kevnlliu** [blockchainuci/s24-jr-smart-contract-to-do-list#3]
### Issue Requirements:
Create a new react component named AddToDoListItemBar in the Src/Components/AddToDoListItemBar/AddToDoListItemBar.jsx file.

Remember, components are like functions that must be exported at the end of the file (look at the ToDoList component for example).

The AddToDoListItemBar should be able to add new [string, boolean] arrays to the toDoItems useState array of the ToDoList component (hint: pass in both the toDoItems and its corresponding useState function as props to AddToDoListItemBar) and should be included at the top of the ToDoList.

The new strings should come from a user input text box and its corresponding button. When the button is pressed, make sure that the user input text box's input is not empty and if it isn't add it to the toDoItems array as [user_string, false].

To test your AddToDoListItemBar component, you can either console log the toDoItems array to track if there are changes or map each item of the toDoItems array to just a <td> tag (later this will be a <ToDoListItem> tag but that is the other task).

Feel free to reach out to me on discord if you have any questions

**Comment by SilXe** [comment]
I tried to test the code by running the react file, but the error message says ToDoListItem is missing. I guess this is because it does not have any access to the component that instantiates ToDoListItem. How do I run a test in this case? Also, I think we don't have write access to this project.

**Comment by kevnlliu** [comment]
ToDoListItem is the component the other team will be creating, so to run the code just comment it out and replace `<ToDoListItem toDoName={element}></ToDoListItem>` 
with 
`<p>element[0]<p>`
I am not quite sure what you mean by you don't have write access to the project?
